### ISSUE TITLE
Wrong text for "errorMessage" into 'login with wrong email format credentials read data from fixture' test

### ISSUE THREAD

**Issue by ZadubinnyiOleksandr** [AZANIR/cypressAllure#1]
Does not pass validate login error becouse error text is incorrect. 
Now error text is 'Invalid email addressssss.' should become 'Invalid email address.'

**Comment by AZANIR** [comment]
> Does not pass validate login error becouse error text is incorrect. Now error text is 'Invalid email addressssss.' should become 'Invalid email address.'

as intended
